application: email2httppost-1008
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/mail/.+
  script: email2httppost.app

inbound_services:
- mail

env_variables:
  DESTINATION_URL: 'http://status.udengi.ru/api/test.php'
  # Whether to log the messages in the database
  COPY_DB: False
  # Whether to forward a copy of the email to another address
  COPY_EMAIL: False
  COPY_EMAIL_TO: 'loonar@gmail.com'
  COPY_EMAIL_FROM: 'noreply@udengi.ru'
  COPY_EMAIL_SUBJECT: 'The subject of the copy mail'



